### ISSUE TITLE
Helper to install selenium

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-behat-extension#129]
Since behat tests are 99% used to drive selenium, it would be good if there was a helper in this module to grab and start the selenium server.

A simple approach would be to require `https://github.com/sveneisenschmidt/selenium-server-standalone`.

A more sophisticated approach would be to start and stop selenium automatically, using the initializer.

**Comment by chillu** [comment]
No longer Selenium based, using Chromedriver woooo!
