### ISSUE TITLE
Typehint on SilverStripeContext::before() incorrect. Breaks any tests using ScenarioOutline

### ISSUE THREAD

**Issue by warslett** [silverstripe/silverstripe-behat-extension#132]
The typehint used for SilverStripeContext::before() on line 185 is ScenarioEvent. The problem with this is that if your features use ScenarioOutline then the event that gets passed is OutlineExampleEvent. This breaks your tests. The correct Typehint IMO should be the parent class of both these events BaseScenarioEvent. I will try to get a pull request in later today.

**Comment by dhensby** [comment]
Please do open a PR :)

**Comment by warslett** [comment]
fixed in https://github.com/silverstripe/silverstripe-behat-extension/issues/136
