### ISSUE TITLE
Errors in SilverStripe::givenTheCurrentTimeIs

### ISSUE THREAD

**Issue by warslett** [silverstripe/silverstripe-behat-extension#133]
This step doesn't work. The parameter in the method signature is $time but the function calls the variable $date. Another separate issue is a call to InvalidArgumentException which has not been included in scope. The result is that instead of getting a helpful exception when your date format is wrong you get a big ugly Exception not found error.

Will put a PR up for this fairly soon because it is blocking me.

**Comment by warslett** [comment]
seems the issue has already been fixed in master. My mistake. I'll close this issue

**Comment by warslett** [comment]
Sorry reopening again. This is not fixed. I was looking at the function givenTheCurrentDateIs where it works fine. I will open a PR.

**Comment by dhensby** [comment]
thanks, fixed in #135
