### ISSUE TITLE
behat --init should add _manifest_exclude to scaffolded php code

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-behat-extension#156]
Otherwise class loader will crash if behat-extension isn't installed.

**Comment by maxime-rainville** [comment]
I'm not 100% sure how I would go about reproducing this. I'll set a low impact for now.

**Comment by robbieaverill** [comment]
To be fair, we don't even need to scaffold any PHP code when initialising behat for modules or projects any more. You can just create a behat.yml that uses the default feature and fixture contexts and get started right away with defining features. In the past you'd have also created your own feature context classes but that's not necessary any more.
