### ISSUE TITLE
Misleading docs ref. Firefox version

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-behat-extension#162]
The installation docs in README.md suggest installing Firefox ESR, stating that it must be a release that’s compatible with Selenium-Webdriver. However, the linked document states:

> Firefox: latest ESR, previous ESR, current release, one previous release

The latest Firefox ESR release doesn’t work with whichever version of Selenium we’re using. I guessed at version 45, downloaded it from here and all is well now: https://ftp.mozilla.org/pub/firefox/releases/45.0.2esr/mac/en-GB/

**Comment by chillu** [comment]
@kinglozzer Yeah thanks for raising that, just hit the same issue. I had to go even older (31.0), using the same version as Travis CI. See https://github.com/silverstripe/silverstripe-behat-extension/pull/166
