### ISSUE TITLE
Move Scrutinizer repo over to "silverstripe"

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-behat-extension#175]
Hey @dhensby, another one of these for you =)

https://scrutinizer-ci.com/g/silverstripe-labs/silverstripe-behat-extension/

**Comment by dhensby** [comment]
I'm not an admin for some reason - I've contacted their support again...

**Comment by robbieaverill** [comment]
Sweet as

**Comment by dhensby** [comment]
@assertchris it looks like you are admin on this scrutinzer - can you add the repo to the silverstripe-labs organisation, please?

**Comment by dhensby** [comment]
Or just make me an admin ;) same as with https://github.com/silverstripe/silverstripe-sharedraftcontent/issues/72#issuecomment-353331568

**Comment by assertchris** [comment]
I've added you to every repo I control on there. Tried to remove myself but apparently I can't.

**Comment by dhensby** [comment]
> I've added you to every repo I control on there. Tried to remove myself but apparently I can't.

thanks @assertchris 🎉

**Comment by dhensby** [comment]
moved over

**Comment by assertchris** [comment]
How did you move it over? Could you do the rest I added you to? I don't wanna be the bottleneck for these kinds of issues...

**Comment by dhensby** [comment]
@assertchris if I'm added to them now, the moving them over will not be an issue going forward :)

It's just updating the repository URL (as we moved a few repos from `silverstripe-labs` to `silverstrip` org
