### ISSUE TITLE
Installation guide version mismatch

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-behat-extension#183]
Hi,

Following the installation guide results in this error:

`Unrecognized option "facebook_web_driver"`

The problem is the default branch on GitHub is `4` and running `composer require --dev silverstripe/behat-extension` pulls down `^3`.

Installing with `composer require --dev silverstripe/behat-extension ^4` resolves the issue.

Not sure if this needs to be a docs change or whether Packagist isn't using the correct default branch?

**Comment by robbieaverill** [comment]
I don't think the 4.x version is stable yet which might be why you get 3.x by default. Perhaps we need to stabilise that release line...

**Comment by maxime-rainville** [comment]
Considering it's running all our builds, I think it's probably good enough to call it stable.

Presumably that's not part of our normal release cycle and we just need to create stable tag?

**Comment by robbieaverill** [comment]
4.0.0 tagged
