### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by altwohill** [silverstripe/silverstripe-behat-extension#187]
Running `vendor/bin/behat-ss @mymodule`

Gives the following error: 

> 'sh'  is not recognized as an internal or external command, operable program or batch file.

event though there is a .bat file in the vendor/bin folder.

**Comment by dnsl48** [comment]
I think that's rather `vendor/bin/behat-ss` itself [is a bash script](https://github.com/silverstripe/silverstripe-behat-extension/blob/4/bin/behat-ss).

You may use `vendor/bin/behat` instead. `vendor/bin/behat-ss` only launches `chromedriver` and `vendor/bin/serve` apart from `vendor/bin/behat`.

I'm actually not sure this script is worth existing at all as it implies you running things locally and not in VMs

**Comment by dnsl48** [comment]
I'd suggest we remove this script completely.
But if someone wants, could rewrite it in PHP.

**Comment by robbieaverill** [comment]
-1 for removing it, I use it all the time. We could easily write an equivalent for Windows though

**Comment by chillu** [comment]
I've clarified in the README that running this script requires bash
