### ISSUE TITLE
Upgrading ModuleClassGuesser to implement new 

### ISSUE THREAD

**Issue by srizzling** [silverstripe/silverstripe-behat-extension#68]
Brain Dumping for my sake :P:

ModuleContextClassGuesser is how we are able to write tests for separate modules by specifying via `@cms` for example. 

https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Specification/Locator/SpecificationLocator.php

SpecficationLocator requires two methods to be implemented:
- `public function getLocatorExamples()` - This method returns documentation/examples for how to specify different locators. Example provided here: https://github.com/Behat/Symfony2Extension/blob/master/src/Behat/Symfony2Extension/Specification/BundleFeatureLocator.php#L42

Subtasks Required to make this extension work:
- [x] Folder Structure needs to change, Need to move ModuleContextClassGuesser into Specfication folder and Create a ModuleContextClassLocator.php in the Specfication namespace
- [x] Depreciated ModuleContextClassGuesser and moved to depreciated folder (for now)
- [x] Make  ModuleContextClassLocator implement SpecificationLocator
- [ ] Need to make Suite Class that encapsulates the SilverStripe Modules 
- [ ] Load locator in the Extension file

**Comment by dhensby** [comment]
This sounds like a new feature rather than a bug and it doesn't appear to have had much progress over the last 4 years.

@srizzling do you have any plans to get this over the line? Perhaps it is and the issue is just stale?

I'm going to close it until we hear back, feel free to reopen
